# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 64bac76fe3e26c5adf98c38878753b2bae9c3e75ad741b1257b9707dd827700a88d83c030fa48b2577439c11825cd22a9fa354b43aefdd24541aa4e862f34a34

test:
  secret_key_base: a55642b8d7af07d13940f68f5cc73c0fc0f6669a568b6bc52ffe4104351190b100c550efa08d091e8c8cbd1082617cb0e0f4af8d6ec762a46b3457b0f6dfe533

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
